#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

nitrogen --restore &

pcmanfm -d &

wmname LG3D

#$HOME/.config/polybar/launch.sh

bspc monitor eDP-1 -d W X Y Z
bspc monitor HDMI-1 -d A B C D

$HOME/.config/polybar/launch.sh

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focused_border_color "#9671D5"
bspc config focus_follows_pointer true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Blueberry.py state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Steam state=floating follow=on
bspc rule -a steam_app_1238840 state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Blueberry.py state=floating manage=on layer=normal sticky=on follow=on
